# default model configuration
architecture: guided_diffusion.model.unet.UNetModel

in_channels: 3
out_channels: 3
image_size: 64
num_channels: 128
num_res_blocks: 2

num_heads: 4
num_heads_upsample: -1
num_head_channels: -1

attention_resolutions: "16,8,4,2"
channel_mult: ""

learn_sigma: False
target_type: ${..diffusion.target_type}

dropout: 0.0

use_scale_shift_norm: True
resblock_updown: False

use_fp16: ${use_fp16}
class_cond: ${class_cond}
use_checkpoint: False
use_new_attention_order: False